const employees = [
  {
    id: 1,
    email: "employee1@example.com",
    password: "123",
    tasks: [
      {
        title: "Fix homepage bug",
        description: "Resolve layout issues on the homepage for mobile view.",
        date: "2025-01-01",
        category: "Development",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Update documentation",
        description: "Revise the onboarding guide for new employees.",
        date: "2025-01-03",
        category: "Documentation",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Weekly team meeting",
        description: "Participate in the weekly team sync-up meeting.",
        date: "2025-01-05",
        category: "Meetings",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
  },
  {
    id: 2,
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        title: "Deploy staging build",
        description: "Deploy the latest build to the staging environment.",
        date: "2025-01-02",
        category: "Deployment",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Bug triage",
        description: "Analyze and categorize reported bugs.",
        date: "2025-01-04",
        category: "Development",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Customer feedback review",
        description: "Review feedback from the support team.",
        date: "2025-01-06",
        category: "Analysis",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Prepare presentation",
        description: "Create slides for the upcoming client meeting.",
        date: "2025-01-07",
        category: "Presentation",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 3,
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        title: "Database backup",
        description: "Perform a full backup of the database.",
        date: "2025-01-03",
        category: "Database",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Optimize query",
        description: "Improve the efficiency of a slow SQL query.",
        date: "2025-01-04",
        category: "Development",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "On-call support",
        description: "Monitor system alerts and address incidents.",
        date: "2025-01-05",
        category: "Support",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 4,
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        title: "UI testing",
        description: "Test the user interface for inconsistencies.",
        date: "2025-01-03",
        category: "Testing",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Fix CSS bugs",
        description: "Resolve visual issues in the CSS stylesheets.",
        date: "2025-01-04",
        category: "Development",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Cross-browser compatibility check",
        description: "Ensure the website works across major browsers.",
        date: "2025-01-05",
        category: "Testing",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
    ],
  },
  {
    id: 5,
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        title: "SEO audit",
        description: "Review the website for SEO improvements.",
        date: "2025-01-01",
        category: "Marketing",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
      {
        title: "Content proofreading",
        description: "Proofread new blog articles before publishing.",
        date: "2025-01-02",
        category: "Content",
        active: false,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Social media plan",
        description: "Create a social media content calendar.",
        date: "2025-01-03",
        category: "Marketing",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Analytics report",
        description: "Generate a performance report using Google Analytics.",
        date: "2025-01-04",
        category: "Analysis",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    email: "admin@example.com",
    password: "123",
  },
];

export const setLocalStorage = () => {};
export const getLocalStorage = () => {};
